# https://github.com/wphillipmoore/standard-actions/blob/develop/.github/workflows/README.md
name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      run-security:
        type: boolean
        default: true
      run-release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-quality.yml@v1.5
    with:
      language: shell
      versions: '["latest"]'
      container-suffix: base

  security:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-security.yml@v1.5
    with:
      language: shell
      run-standards: ${{ inputs.run-release != 'false' }}
      run-security: ${{ inputs.run-security != 'false' }}
      run-codeql: false
    permissions:
      contents: read
      security-events: write

  version:
    uses: wphillipmoore/standard-actions/.github/workflows/ci-version-bump.yml@v1.5
    with:
      language: shell
      run-release: ${{ inputs.run-release != 'false' }}
